# nginx-vulnerable-proxy.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vulnerable-config
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        # VULNERABILITY 1: Exposed server tokens
        server_tokens on;
        
        # VULNERABILITY 2: No rate limiting
        
        server {
            listen 80;
            server_name _;
            
            # VULNERABILITY 3: Debug endpoints exposed
            location /nginx_status {
                stub_status on;
            }
            
            # Main API proxy
            location /api/ {
                # VULNERABILITY 4: Improper proxy_pass configuration
                # Allows path traversal: /api/../internal/
                proxy_pass http://flask-api-svc.default.svc.cluster.local:5000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            
            # VULNERABILITY 5: Internal endpoints accessible
            location /internal/ {
                # Should be blocked but isn't
                proxy_pass http://flask-api-svc.default.svc.cluster.local:5000/;
            }
            
            # VULNERABILITY 6: Admin panel exposed without auth
            location /admin {
                proxy_pass http://flask-api-svc.default.svc.cluster.local:5000/admin;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vulnerable-proxy
  namespace: default
  labels:
    app: nginx-proxy
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
      - name: config
        configMap:
          name: nginx-vulnerable-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-svc
  namespace: default
spec:
  selector:
    app: nginx-proxy
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: LoadBalancer  # Exposed to internet
