apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-sample
  namespace: default
spec:
  rayVersion: '2.8.0'
  
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
      num-cpus: '0'
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.8.0-py310
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          - containerPort: 8000
            name: serve
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
          - name: log-volume
            mountPath: /tmp/ray
        volumes:
        - name: log-volume
          emptyDir: {}
  
  workerGroupSpecs:
  - groupName: small-group
    replicas: 2
    minReplicas: 1
    maxReplicas: 3
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:2.8.0-py310
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
          - name: log-volume
            mountPath: /tmp/ray
        volumes:
        - name: log-volume
          emptyDir: {}
  
  - groupName: gpu-group
    replicas: 1
    minReplicas: 0
    maxReplicas: 1
    rayStartParams:
      num-gpus: "1"
    template:
      spec:
        nodeSelector:
          name: gpu-pool2
        tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        containers:
        - name: ray-worker-gpu
          image: rayproject/ray:2.8.0-py310-gpu
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: 4Gi
              nvidia.com/gpu: "1"
          volumeMounts:
          - name: log-volume
            mountPath: /tmp/ray
        volumes:
        - name: log-volume
          emptyDir: {}
